### ISSUE TITLE
Typo missing comma, Installation fails

### ISSUE THREAD

**Issue by nipuquayum** [sidatasciencelab/gender-spacy#2]
`setup.py` line 20 is missing a comma for which installation fails.

**Comment by wjbmattingly** [comment]
Thanks for this! I did not receive the notification for some reason. I am returning to this now, so I will be sure to merge your PR before I make any further updates.

**Comment by wjbmattingly** [comment]
I'm pleased to announce that the issue you've been experiencing has been resolved with the latest commit [Commit 42ee2ac](https://github.com/sidatasciencelab/gender-spacy/commit/42ee2acdbe05ee748c2dda75319300fe81e6229f). This commit includes necessary updates to the setup.py file, addressing dependency issues related to spacy-experimental.

In addition, the package version has been incremented to 0.0.5 to reflect these changes and improvements. This update should ensure better stability and compatibility, especially for environments like M2 chip Macs in VS Code.

Please try out the new version and let us know if it resolves the issue on your end. Your feedback is invaluable to us, and we're committed to improving gender-spacy for all users. Thank you for your patience and support!

For detailed information about the changes, you can refer to the commit here:
[Commit 42ee2ac](https://github.com/sidatasciencelab/gender-spacy/commit/42ee2acdbe05ee748c2dda75319300fe81e6229f)
